# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='ghtopdep',
    version='0.3.12',
    description='CLI tool for sorting dependents repositories and packages by stars',
    python_requires='==3.*,>=3.5.0',
    author='Andriy Orehov',
    author_email='andriyorehov@gmail.com',
    license='MIT',
    entry_points={"console_scripts": ["ghtopdep = ghtopdep.ghtopdep:cli"]},
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'appdirs==1.*,>=1.4.3', 'cachecontrol==0.*,>=0.12.5',
        'click==7.*,>=7.0.0', 'github3.py==1.*,>=1.3.0', 'halo==0.*,>=0.0.26',
        'lockfile==0.*,>=0.12.2', 'pipdate==0.*,>=0.3.4',
        'requests==2.*,>=2.22.0', 'selectolax==0.*,>=0.1.13',
        'tabulate==0.*,>=0.8.3'
    ],
    extras_require={
        "dev": ["better-exceptions==0.*,>=0.2.2", "pysnooper==0.*,>=0.3.0"]
    },
)
